### PR TITLE
RockPaperScissors

### PR DESCRIPTION
**Pull request by yusufidimaina9989**

### CODE REVIEW

**Review by xhliu — CHANGES_REQUESTED** [review]
Commit when deploying, and reveal when calling. https://github.com/sCrypt-Inc/boilerplate/issues/288

Also add testing.

**Comment by yusufidimaina9989** [comment]
> Commit when deploying, and reveal when calling. https://github.com/sCrypt-Inc/boilerplate/issues/288
> 
> Also add testing.

Ok sir, I understand

**Comment by msinkec** [comment]
@yusufidimaina9989 

I've refactored the contract:

- Added salt to commitments.
- Simplified winner pick logic.
- Enforced outputs. This is needed because of the 50/50 split case.
- No sig needed, since the contract enforces outputs anyways.
- Syntax corrections; variable names shouldn't start capitalized unless its a constant.
- Contract filenames shouldn't start capitalized either to keep it consistent with the past contracts.

Additionally the test you wrote doesn't get invoked at all. You are trying to invoke the `callContract` function from within the function itself. This call should be outside the function. See the test of the `Demo` contract to see how it should be done correctly.

This seems to also be the case for some other tests. I'll open a separate issue for fixing those.

Please finish the test for RockPaperScissiors2. I think for the most part you only need to bind a custom tx builder to enforce the players payment outputs.

**Review by yusufidimaina9989 — COMMENTED** [review]
` assert(
            hash256(int2ByteString(playerAMove, 1n) + playerASalt) ==
                this.playerAHash,
            'Invalid move'
        )
        assert(
            hash256(int2ByteString(playerBMove, 1n) + playerBSalt) ==
                this.playerBHash,
            'Invalid move'
        )`
this `hash256` will always give `invalid move` i use `Sha256` rather
@msinkec

**Comment by msinkec** [comment]
> ` assert( hash256(int2ByteString(playerAMove, 1n) + playerASalt) == this.playerAHash, 'Invalid move' ) assert( hash256(int2ByteString(playerBMove, 1n) + playerBSalt) == this.playerBHash, 'Invalid move' )`
> 
> this `hash256` will always give `invalid move` i use `Sha256` rather @msinkec

thats fine

**Pull request merged**
